profiler:
  prometheus: false
  statsd_address: none
  service: none

mysql:
  host: localhost
  user: root
  password: 123123
  name_db: flowareonline
  debug: true

mongodb:
  host: cluster0-shard-00-00-fpd2h.gcp.mongodb.net:27017,cluster0-shard-00-01-fpd2h.gcp.mongodb.net:27017,cluster0-shard-00-02-fpd2h.gcp.mongodb.net:27017
  database: flowareonline
  database_oit: iot
  user: floware
  pass: floware2020
  
encryption:
  oid_key: floware
  jwt_secret: secret
  jwt_exp: 72
  jwt_pol: 59a795909e65177c27fcdd87

partner:
  url_devices: ''
  url_metric_gps: ''
